### ISSUE TITLE
Missing visitor-keys

### ISSUE THREAD

**Issue by armano2** [eslint/typescript-eslint-parser#555]
I did some checking what we can and what we are not able to visit and i found some missing stuff:

#### missing `typeParameters`
- [x] NewExpression - `new foo<Foo>()` #565
- [x] CallExpression - `foo<Foo>()` #565
- [x] TSAbstractClassDeclaration:  #561 - `abstract class Foo<Bar> {}`

#### missing `superTypeParameters` 
`class foo extends bar<Foo>`
- [x] ClassDeclaration: #561
- [x] ClassExpression: #561
- [x] TSAbstractClassDeclaration: #561

#### missing `implements`
`class foo implements bar`,  `class foo implements bar, baz` 
- [x] ClassDeclaration: #562
- [x] ClassExpression: #562
- [x] TSAbstractClassDeclaration: #562

#### missing import equals
`import foo = require('foo')`
- [x] TSImportEqualsDeclaration #571
  - name
  - moduleReference
- [x] TSExternalModuleReference #571
  - expression

#### invalid order:
- [x] TSAbstractClassProperty : #560
  - key
  - typeAnnotation
  - value

#### missing decorators:
- [x] TSAbstractClassProperty: #560
- [x] TSAbstractClassDeclaration #561

**Comment by armano2** [comment]
small update

**Comment by mysticatea** [comment]
No. 

TypeScript has two namespaces: variables and types.

```ts
// Those are not redeclaration 
// because `interface` defines only in types and `const` defines only in variables.
interface A {}
const A = 0

// On the other hand, `class` defines in both types and variables.
class B {}
```

Then, the `scopeManager` doesn't have types.
I think that we should provide a way to access `types` namespace, but we don't have it now.

**Comment by armano2** [comment]
ok, i was thinking correctly,

i just wanted to confirm that :)
