### ISSUE TITLE
Milestone: Decorator Support

### ISSUE THREAD

**Issue by JamesHenry** [eslint/typescript-eslint-parser#63]
This issue it to track progress against supporting decorators within the final AST that the parser produces. We currently remove them during parsing.

We need to ensure that the following are accurately carried over from the original TypeScript AST:

- [x] Parameter Decorators
 - [x] On instance member
 - [x] On static member
 - [x] In constructor
- [x] Method Decorators
 - [x] On instance member
 - [x] On static member
- [x] Accessor Decorators
 - [x] On instance member
 - [x] On static member
- [x] Property Decorators
 - [x] On instance member
 - [x] On static member
- [x] Class Decorators

We also need to account for the difference between decorators and decorator factories:

**Decorator:**
![unspecified-11](https://cloud.githubusercontent.com/assets/900523/17868173/a20191a2-68a5-11e6-8808-a85e97be70b6.png)

**Decorator Factory:**
![unspecified-12](https://cloud.githubusercontent.com/assets/900523/17868172/a0dcc9fe-68a5-11e6-8ab6-7f6db611af56.png)

At the AST-level, the decorator node has an `Identifier` TSNode as an `expression`, whereas the decorator factory has a `CallExpression` TSNode.

Decorators are not currently covered by the ESTree spec as they are still a fairly early-stage es-proposal, but Angular 2, for example, has adopted them as a core aspect of the framework.

TypeScript adds a `decorators` array to the node in question, and I propose we do the same. 

Resources:
https://www.typescriptlang.org/docs/handbook/decorators.html

**Comment by nzakas** [comment]
> TypeScript adds a decorators array to the node in question, and I propose we do the same.

Agreed. 

It's probably worth looking at the AST that Babel produces for decorators, which I'm guessing is similar.

**Comment by JamesHenry** [comment]
Good thinking! 

astexplorer shows that babel-eslint produces near identical output, with both the decorator and decorator factory nodes (within a `decorators` array on the `MethodDefinition`) having a type of `Decorator` and an `expression` property.

As described above, the `expression` is an `Identifier` for the decorator, and a `CallExpression` for the decorator factory.

![aug-22-2016 21-40-33](https://cloud.githubusercontent.com/assets/900523/17870862/217eeeba-68b1-11e6-8f17-6d720de65800.gif)

Here is a PR https://github.com/eslint/typescript-eslint-parser/pull/64 for a Parameter Decorator and a Parameter Decorator Factory on an instance method to get the ball rolling and confirm the format with you.

Feel free to leave it open until more cases are added, but I need to break off now as it's quite late here.

**Comment by nzakas** [comment]
Makes sense. Bonus points for the animated demo. :)

**Comment by nzakas** [comment]
It looks like Flow does support decorators, and it's with the `decorators` array with `Identifier` or `CallExpression` as items, so probably best to mimic that.

**Comment by JamesHenry** [comment]
Ok, cool thanks. Do you have a reference for that you can link to?

I will update that first PR now

**Comment by nzakas** [comment]
I just used astexplorer.net.

**Comment by JamesHenry** [comment]
Method decorator support (static and instance methods) now complete in https://github.com/eslint/typescript-eslint-parser/pull/64

**Comment by JamesHenry** [comment]
Class decorator support now also complete. I branched from the method decorator PR to avoid conflicts

**Comment by JamesHenry** [comment]
It appears that flow does not currently support Parameter Decorators.

I think it make sense to just follow the same approach as with the other decorator types - a `decorators` array on the parameter identifier node directly

**Comment by nzakas** [comment]
Agreed.

**Comment by JamesHenry** [comment]
Cool, thanks. In which case PR for parameter decorators is ready https://github.com/eslint/typescript-eslint-parser/pull/69

**Comment by JamesHenry** [comment]
Property decorators up next! https://github.com/eslint/typescript-eslint-parser/pull/72

**Comment by nzakas** [comment]
You are rocking!

**Comment by JamesHenry** [comment]
🎸

**Comment by nzakas** [comment]
@JamesHenry you are awesome. Thanks for all your work on this.

**Comment by JamesHenry** [comment]
Thanks so much @nzakas! Your patience and guidance has been invaluable throughout this process
